query getCronJobs ($first: Int!, $page: Int, $orderBy: [OrderByClause!], $search: String) {
  getCronJobs(
    first: $first
    page: $page
    orderBy: $orderBy
    search: $search
  ) {
    paginatorInfo {
      currentPage
      hasMorePages,
      total,
      count
    }
    data {
      id
      cron_job_id
      name
    }
  }
}
